# Generated by Django 4.0 on 2022-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Enter question', max_length=200)),
                ('optionA', models.CharField(default='Option A', max_length=200)),
                ('optionB', models.CharField(default='Option B', max_length=200)),
                ('optionC', models.CharField(default='Option C', max_length=200)),
                ('optionD', models.CharField(default='Option D', max_length=200)),
                ('Answer', models.CharField(default='Answer', max_length=200)),
            ],
        ),
    ]
