# Generated by Django 4.0 on 2022-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default='+234', max_length=100),
        ),
    ]
