# Generated by Django 4.0 on 2022-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='+234', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
