# Generated by Django 4.0 on 2022-11-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_code_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exam_taken',
            field=models.BooleanField(default=False),
        ),
    ]
